// This file is auto-generated by @hey-api/openapi-ts

import {
  http,
  type HttpHandler,
  HttpResponse,
  type HttpResponseResolver,
  type RequestHandlerOptions as RequestHandlerOptions2,
} from "msw";

import type {
  ClientOptions,
  DeliverySlipsCancelData,
  DeliverySlipsCancelResponses,
  DeliverySlipsCreateData,
  DeliverySlipsCreateResponses,
  DeliverySlipsIndexResponses,
  DeliverySlipsShowResponses,
  DeliverySlipsTemplatesIndexResponses,
  DeliverySlipsUncancelData,
  DeliverySlipsUncancelResponses,
  DeliverySlipsUpdateData,
  DeliverySlipsUpdateResponses,
  InvoicesCancelData,
  InvoicesCancelResponses,
  InvoicesCreateData,
  InvoicesCreateResponses,
  InvoicesIndexResponses,
  InvoicesShowResponses,
  InvoicesTemplatesIndexResponses,
  InvoicesUncancelData,
  InvoicesUncancelResponses,
  InvoicesUpdateData,
  InvoicesUpdateResponses,
  PaymentNoticesCancelData,
  PaymentNoticesCancelResponses,
  PaymentNoticesCreateData,
  PaymentNoticesCreateResponses,
  PaymentNoticesIndexResponses,
  PaymentNoticesShowResponses,
  PaymentNoticesTemplatesIndexResponses,
  PaymentNoticesUncancelData,
  PaymentNoticesUncancelResponses,
  PaymentNoticesUpdateData,
  PaymentNoticesUpdateResponses,
  PurchaseOrdersCancelData,
  PurchaseOrdersCancelResponses,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateResponses,
  PurchaseOrdersIndexResponses,
  PurchaseOrdersShowResponses,
  PurchaseOrdersTemplatesIndexResponses,
  PurchaseOrdersUncancelData,
  PurchaseOrdersUncancelResponses,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateResponses,
  QuotationsCancelData,
  QuotationsCancelResponses,
  QuotationsCreateData,
  QuotationsCreateResponses,
  QuotationsIndexResponses,
  QuotationsShowResponses,
  QuotationsTemplatesIndexResponses,
  QuotationsUncancelData,
  QuotationsUncancelResponses,
  QuotationsUpdateData,
  QuotationsUpdateResponses,
  ReceiptsCancelData,
  ReceiptsCancelResponses,
  ReceiptsCreateData,
  ReceiptsCreateResponses,
  ReceiptsIndexResponses,
  ReceiptsShowResponses,
  ReceiptsTemplatesIndexResponses,
  ReceiptsUncancelData,
  ReceiptsUncancelResponses,
  ReceiptsUpdateData,
  ReceiptsUpdateResponses,
} from "./types.gen";

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions["baseUrl"];
  responseFallback?: "error" | "passthrough";
};

export type HandleDeliverySlipsIndexResponse = {
  body: DeliverySlipsIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /delivery_slips` operation.
 */
export function handleDeliverySlipsIndex(
  response?: HandleDeliverySlipsIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/delivery_slips`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsCreateResponse = {
  body: DeliverySlipsCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /delivery_slips` operation.
 */
export function handleDeliverySlipsCreate(
  response?:
    | HandleDeliverySlipsCreateResponse
    | HttpResponseResolver<never, DeliverySlipsCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, DeliverySlipsCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/delivery_slips`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsTemplatesIndexResponse = {
  body: DeliverySlipsTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /delivery_slips/templates` operation.
 */
export function handleDeliverySlipsTemplatesIndex(
  response?: HandleDeliverySlipsTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/delivery_slips/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsShowResponse = {
  body: DeliverySlipsShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /delivery_slips/{id}` operation.
 */
export function handleDeliverySlipsShow(
  response?:
    | HandleDeliverySlipsShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/delivery_slips/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsUpdateResponse = {
  body: DeliverySlipsUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /delivery_slips/{id}` operation.
 */
export function handleDeliverySlipsUpdate(
  response?:
    | HandleDeliverySlipsUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        DeliverySlipsUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    DeliverySlipsUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/delivery_slips/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsCancelResponse = {
  body: DeliverySlipsCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /delivery_slips/{id}/cancel` operation.
 */
export function handleDeliverySlipsCancel(
  response?:
    | HandleDeliverySlipsCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        DeliverySlipsCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    DeliverySlipsCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/delivery_slips/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleDeliverySlipsUncancelResponse = {
  body: DeliverySlipsUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /delivery_slips/{id}/uncancel` operation.
 */
export function handleDeliverySlipsUncancel(
  response?:
    | HandleDeliverySlipsUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        DeliverySlipsUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    DeliverySlipsUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/delivery_slips/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesIndexResponse = {
  body: InvoicesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /invoices` operation.
 */
export function handleInvoicesIndex(
  response?: HandleInvoicesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/invoices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesCreateResponse = {
  body: InvoicesCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /invoices` operation.
 */
export function handleInvoicesCreate(
  response?: HandleInvoicesCreateResponse | HttpResponseResolver<never, InvoicesCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, InvoicesCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/invoices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesTemplatesIndexResponse = {
  body: InvoicesTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /invoices/templates` operation.
 */
export function handleInvoicesTemplatesIndex(
  response?: HandleInvoicesTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/invoices/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesShowResponse = {
  body: InvoicesShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /invoices/{id}` operation.
 */
export function handleInvoicesShow(
  response?:
    | HandleInvoicesShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/invoices/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesUpdateResponse = {
  body: InvoicesUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /invoices/{id}` operation.
 */
export function handleInvoicesUpdate(
  response?:
    | HandleInvoicesUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        InvoicesUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    InvoicesUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/invoices/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesCancelResponse = {
  body: InvoicesCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /invoices/{id}/cancel` operation.
 */
export function handleInvoicesCancel(
  response?:
    | HandleInvoicesCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        InvoicesCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    InvoicesCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/invoices/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleInvoicesUncancelResponse = {
  body: InvoicesUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /invoices/{id}/uncancel` operation.
 */
export function handleInvoicesUncancel(
  response?:
    | HandleInvoicesUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        InvoicesUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    InvoicesUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/invoices/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesIndexResponse = {
  body: PaymentNoticesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /payment_notices` operation.
 */
export function handlePaymentNoticesIndex(
  response?: HandlePaymentNoticesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/payment_notices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesCreateResponse = {
  body: PaymentNoticesCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /payment_notices` operation.
 */
export function handlePaymentNoticesCreate(
  response?:
    | HandlePaymentNoticesCreateResponse
    | HttpResponseResolver<never, PaymentNoticesCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, PaymentNoticesCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/payment_notices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesTemplatesIndexResponse = {
  body: PaymentNoticesTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /payment_notices/templates` operation.
 */
export function handlePaymentNoticesTemplatesIndex(
  response?: HandlePaymentNoticesTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/payment_notices/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesShowResponse = {
  body: PaymentNoticesShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /payment_notices/{id}` operation.
 */
export function handlePaymentNoticesShow(
  response?:
    | HandlePaymentNoticesShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/payment_notices/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesUpdateResponse = {
  body: PaymentNoticesUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /payment_notices/{id}` operation.
 */
export function handlePaymentNoticesUpdate(
  response?:
    | HandlePaymentNoticesUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PaymentNoticesUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PaymentNoticesUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/payment_notices/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesCancelResponse = {
  body: PaymentNoticesCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /payment_notices/{id}/cancel` operation.
 */
export function handlePaymentNoticesCancel(
  response?:
    | HandlePaymentNoticesCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PaymentNoticesCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PaymentNoticesCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/payment_notices/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePaymentNoticesUncancelResponse = {
  body: PaymentNoticesUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /payment_notices/{id}/uncancel` operation.
 */
export function handlePaymentNoticesUncancel(
  response?:
    | HandlePaymentNoticesUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PaymentNoticesUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PaymentNoticesUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/payment_notices/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersIndexResponse = {
  body: PurchaseOrdersIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /purchase_orders` operation.
 */
export function handlePurchaseOrdersIndex(
  response?: HandlePurchaseOrdersIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/purchase_orders`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersCreateResponse = {
  body: PurchaseOrdersCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /purchase_orders` operation.
 */
export function handlePurchaseOrdersCreate(
  response?:
    | HandlePurchaseOrdersCreateResponse
    | HttpResponseResolver<never, PurchaseOrdersCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, PurchaseOrdersCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/purchase_orders`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersTemplatesIndexResponse = {
  body: PurchaseOrdersTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /purchase_orders/templates` operation.
 */
export function handlePurchaseOrdersTemplatesIndex(
  response?: HandlePurchaseOrdersTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/purchase_orders/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersShowResponse = {
  body: PurchaseOrdersShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /purchase_orders/{id}` operation.
 */
export function handlePurchaseOrdersShow(
  response?:
    | HandlePurchaseOrdersShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/purchase_orders/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersUpdateResponse = {
  body: PurchaseOrdersUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /purchase_orders/{id}` operation.
 */
export function handlePurchaseOrdersUpdate(
  response?:
    | HandlePurchaseOrdersUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PurchaseOrdersUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PurchaseOrdersUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/purchase_orders/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersCancelResponse = {
  body: PurchaseOrdersCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /purchase_orders/{id}/cancel` operation.
 */
export function handlePurchaseOrdersCancel(
  response?:
    | HandlePurchaseOrdersCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PurchaseOrdersCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PurchaseOrdersCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/purchase_orders/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePurchaseOrdersUncancelResponse = {
  body: PurchaseOrdersUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /purchase_orders/{id}/uncancel` operation.
 */
export function handlePurchaseOrdersUncancel(
  response?:
    | HandlePurchaseOrdersUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        PurchaseOrdersUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    PurchaseOrdersUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/purchase_orders/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsIndexResponse = {
  body: QuotationsIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /quotations` operation.
 */
export function handleQuotationsIndex(
  response?: HandleQuotationsIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/quotations`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsCreateResponse = {
  body: QuotationsCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /quotations` operation.
 */
export function handleQuotationsCreate(
  response?:
    | HandleQuotationsCreateResponse
    | HttpResponseResolver<never, QuotationsCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, QuotationsCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/quotations`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsTemplatesIndexResponse = {
  body: QuotationsTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /quotations/templates` operation.
 */
export function handleQuotationsTemplatesIndex(
  response?: HandleQuotationsTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/quotations/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsShowResponse = {
  body: QuotationsShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /quotations/{id}` operation.
 */
export function handleQuotationsShow(
  response?:
    | HandleQuotationsShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/quotations/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsUpdateResponse = {
  body: QuotationsUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /quotations/{id}` operation.
 */
export function handleQuotationsUpdate(
  response?:
    | HandleQuotationsUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        QuotationsUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    QuotationsUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/quotations/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsCancelResponse = {
  body: QuotationsCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /quotations/{id}/cancel` operation.
 */
export function handleQuotationsCancel(
  response?:
    | HandleQuotationsCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        QuotationsCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    QuotationsCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/quotations/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleQuotationsUncancelResponse = {
  body: QuotationsUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /quotations/{id}/uncancel` operation.
 */
export function handleQuotationsUncancel(
  response?:
    | HandleQuotationsUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        QuotationsUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    QuotationsUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/quotations/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsIndexResponse = {
  body: ReceiptsIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /receipts` operation.
 */
export function handleReceiptsIndex(
  response?: HandleReceiptsIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/receipts`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsCreateResponse = {
  body: ReceiptsCreateResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /receipts` operation.
 */
export function handleReceiptsCreate(
  response?: HandleReceiptsCreateResponse | HttpResponseResolver<never, ReceiptsCreateData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, ReceiptsCreateData["body"]>(
    `${options?.baseUrl ?? "*"}/receipts`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsTemplatesIndexResponse = {
  body: ReceiptsTemplatesIndexResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /receipts/templates` operation.
 */
export function handleReceiptsTemplatesIndex(
  response?: HandleReceiptsTemplatesIndexResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "*"}/receipts/templates`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsShowResponse = {
  body: ReceiptsShowResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /receipts/{id}` operation.
 */
export function handleReceiptsShow(
  response?:
    | HandleReceiptsShowResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? "*"}/receipts/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsUpdateResponse = {
  body: ReceiptsUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /receipts/{id}` operation.
 */
export function handleReceiptsUpdate(
  response?:
    | HandleReceiptsUpdateResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        ReceiptsUpdateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    ReceiptsUpdateData["body"]
  >(
    `${options?.baseUrl ?? "*"}/receipts/:id`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsCancelResponse = {
  body: ReceiptsCancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /receipts/{id}/cancel` operation.
 */
export function handleReceiptsCancel(
  response?:
    | HandleReceiptsCancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        ReceiptsCancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    ReceiptsCancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/receipts/:id/cancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleReceiptsUncancelResponse = {
  body: ReceiptsUncancelResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /receipts/{id}/uncancel` operation.
 */
export function handleReceiptsUncancel(
  response?:
    | HandleReceiptsUncancelResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        ReceiptsUncancelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    ReceiptsUncancelData["body"]
  >(
    `${options?.baseUrl ?? "*"}/receipts/:id/uncancel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type MswHandlerFactories = {
  /**
   * Handler for the `GET /delivery_slips` operation.
   */
  deliverySlipsIndex: typeof handleDeliverySlipsIndex;
  /**
   * Handler for the `POST /delivery_slips` operation.
   */
  deliverySlipsCreate: typeof handleDeliverySlipsCreate;
  /**
   * Handler for the `GET /delivery_slips/templates` operation.
   */
  deliverySlipsTemplatesIndex: typeof handleDeliverySlipsTemplatesIndex;
  /**
   * Handler for the `GET /delivery_slips/{id}` operation.
   */
  deliverySlipsShow: typeof handleDeliverySlipsShow;
  /**
   * Handler for the `PUT /delivery_slips/{id}` operation.
   */
  deliverySlipsUpdate: typeof handleDeliverySlipsUpdate;
  /**
   * Handler for the `PUT /delivery_slips/{id}/cancel` operation.
   */
  deliverySlipsCancel: typeof handleDeliverySlipsCancel;
  /**
   * Handler for the `PUT /delivery_slips/{id}/uncancel` operation.
   */
  deliverySlipsUncancel: typeof handleDeliverySlipsUncancel;
  /**
   * Handler for the `GET /invoices` operation.
   */
  invoicesIndex: typeof handleInvoicesIndex;
  /**
   * Handler for the `POST /invoices` operation.
   */
  invoicesCreate: typeof handleInvoicesCreate;
  /**
   * Handler for the `GET /invoices/templates` operation.
   */
  invoicesTemplatesIndex: typeof handleInvoicesTemplatesIndex;
  /**
   * Handler for the `GET /invoices/{id}` operation.
   */
  invoicesShow: typeof handleInvoicesShow;
  /**
   * Handler for the `PUT /invoices/{id}` operation.
   */
  invoicesUpdate: typeof handleInvoicesUpdate;
  /**
   * Handler for the `PUT /invoices/{id}/cancel` operation.
   */
  invoicesCancel: typeof handleInvoicesCancel;
  /**
   * Handler for the `PUT /invoices/{id}/uncancel` operation.
   */
  invoicesUncancel: typeof handleInvoicesUncancel;
  /**
   * Handler for the `GET /payment_notices` operation.
   */
  paymentNoticesIndex: typeof handlePaymentNoticesIndex;
  /**
   * Handler for the `POST /payment_notices` operation.
   */
  paymentNoticesCreate: typeof handlePaymentNoticesCreate;
  /**
   * Handler for the `GET /payment_notices/templates` operation.
   */
  paymentNoticesTemplatesIndex: typeof handlePaymentNoticesTemplatesIndex;
  /**
   * Handler for the `GET /payment_notices/{id}` operation.
   */
  paymentNoticesShow: typeof handlePaymentNoticesShow;
  /**
   * Handler for the `PUT /payment_notices/{id}` operation.
   */
  paymentNoticesUpdate: typeof handlePaymentNoticesUpdate;
  /**
   * Handler for the `PUT /payment_notices/{id}/cancel` operation.
   */
  paymentNoticesCancel: typeof handlePaymentNoticesCancel;
  /**
   * Handler for the `PUT /payment_notices/{id}/uncancel` operation.
   */
  paymentNoticesUncancel: typeof handlePaymentNoticesUncancel;
  /**
   * Handler for the `GET /purchase_orders` operation.
   */
  purchaseOrdersIndex: typeof handlePurchaseOrdersIndex;
  /**
   * Handler for the `POST /purchase_orders` operation.
   */
  purchaseOrdersCreate: typeof handlePurchaseOrdersCreate;
  /**
   * Handler for the `GET /purchase_orders/templates` operation.
   */
  purchaseOrdersTemplatesIndex: typeof handlePurchaseOrdersTemplatesIndex;
  /**
   * Handler for the `GET /purchase_orders/{id}` operation.
   */
  purchaseOrdersShow: typeof handlePurchaseOrdersShow;
  /**
   * Handler for the `PUT /purchase_orders/{id}` operation.
   */
  purchaseOrdersUpdate: typeof handlePurchaseOrdersUpdate;
  /**
   * Handler for the `PUT /purchase_orders/{id}/cancel` operation.
   */
  purchaseOrdersCancel: typeof handlePurchaseOrdersCancel;
  /**
   * Handler for the `PUT /purchase_orders/{id}/uncancel` operation.
   */
  purchaseOrdersUncancel: typeof handlePurchaseOrdersUncancel;
  /**
   * Handler for the `GET /quotations` operation.
   */
  quotationsIndex: typeof handleQuotationsIndex;
  /**
   * Handler for the `POST /quotations` operation.
   */
  quotationsCreate: typeof handleQuotationsCreate;
  /**
   * Handler for the `GET /quotations/templates` operation.
   */
  quotationsTemplatesIndex: typeof handleQuotationsTemplatesIndex;
  /**
   * Handler for the `GET /quotations/{id}` operation.
   */
  quotationsShow: typeof handleQuotationsShow;
  /**
   * Handler for the `PUT /quotations/{id}` operation.
   */
  quotationsUpdate: typeof handleQuotationsUpdate;
  /**
   * Handler for the `PUT /quotations/{id}/cancel` operation.
   */
  quotationsCancel: typeof handleQuotationsCancel;
  /**
   * Handler for the `PUT /quotations/{id}/uncancel` operation.
   */
  quotationsUncancel: typeof handleQuotationsUncancel;
  /**
   * Handler for the `GET /receipts` operation.
   */
  receiptsIndex: typeof handleReceiptsIndex;
  /**
   * Handler for the `POST /receipts` operation.
   */
  receiptsCreate: typeof handleReceiptsCreate;
  /**
   * Handler for the `GET /receipts/templates` operation.
   */
  receiptsTemplatesIndex: typeof handleReceiptsTemplatesIndex;
  /**
   * Handler for the `GET /receipts/{id}` operation.
   */
  receiptsShow: typeof handleReceiptsShow;
  /**
   * Handler for the `PUT /receipts/{id}` operation.
   */
  receiptsUpdate: typeof handleReceiptsUpdate;
  /**
   * Handler for the `PUT /receipts/{id}/cancel` operation.
   */
  receiptsCancel: typeof handleReceiptsCancel;
  /**
   * Handler for the `PUT /receipts/{id}/uncancel` operation.
   */
  receiptsUncancel: typeof handleReceiptsUncancel;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?:
        | Parameters<MswHandlerFactories[K]>[0]
        | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
  type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult["pick"] = {
    deliverySlipsIndex: wrap(handleDeliverySlipsIndex),
    deliverySlipsCreate: wrap(handleDeliverySlipsCreate),
    deliverySlipsTemplatesIndex: wrap(handleDeliverySlipsTemplatesIndex),
    deliverySlipsShow: wrap(handleDeliverySlipsShow),
    deliverySlipsUpdate: wrap(handleDeliverySlipsUpdate),
    deliverySlipsCancel: wrap(handleDeliverySlipsCancel),
    deliverySlipsUncancel: wrap(handleDeliverySlipsUncancel),
    invoicesIndex: wrap(handleInvoicesIndex),
    invoicesCreate: wrap(handleInvoicesCreate),
    invoicesTemplatesIndex: wrap(handleInvoicesTemplatesIndex),
    invoicesShow: wrap(handleInvoicesShow),
    invoicesUpdate: wrap(handleInvoicesUpdate),
    invoicesCancel: wrap(handleInvoicesCancel),
    invoicesUncancel: wrap(handleInvoicesUncancel),
    paymentNoticesIndex: wrap(handlePaymentNoticesIndex),
    paymentNoticesCreate: wrap(handlePaymentNoticesCreate),
    paymentNoticesTemplatesIndex: wrap(handlePaymentNoticesTemplatesIndex),
    paymentNoticesShow: wrap(handlePaymentNoticesShow),
    paymentNoticesUpdate: wrap(handlePaymentNoticesUpdate),
    paymentNoticesCancel: wrap(handlePaymentNoticesCancel),
    paymentNoticesUncancel: wrap(handlePaymentNoticesUncancel),
    purchaseOrdersIndex: wrap(handlePurchaseOrdersIndex),
    purchaseOrdersCreate: wrap(handlePurchaseOrdersCreate),
    purchaseOrdersTemplatesIndex: wrap(handlePurchaseOrdersTemplatesIndex),
    purchaseOrdersShow: wrap(handlePurchaseOrdersShow),
    purchaseOrdersUpdate: wrap(handlePurchaseOrdersUpdate),
    purchaseOrdersCancel: wrap(handlePurchaseOrdersCancel),
    purchaseOrdersUncancel: wrap(handlePurchaseOrdersUncancel),
    quotationsIndex: wrap(handleQuotationsIndex),
    quotationsCreate: wrap(handleQuotationsCreate),
    quotationsTemplatesIndex: wrap(handleQuotationsTemplatesIndex),
    quotationsShow: wrap(handleQuotationsShow),
    quotationsUpdate: wrap(handleQuotationsUpdate),
    quotationsCancel: wrap(handleQuotationsCancel),
    quotationsUncancel: wrap(handleQuotationsUncancel),
    receiptsIndex: wrap(handleReceiptsIndex),
    receiptsCreate: wrap(handleReceiptsCreate),
    receiptsTemplatesIndex: wrap(handleReceiptsTemplatesIndex),
    receiptsShow: wrap(handleReceiptsShow),
    receiptsUpdate: wrap(handleReceiptsUpdate),
    receiptsCancel: wrap(handleReceiptsCancel),
    receiptsUncancel: wrap(handleReceiptsUncancel),
  };
  const all: CreateMswHandlersResult["all"] = (options = {}) => {
    type OverrideValue<R> = R | [response?: R, options?: RequestHandlerOptions];
    function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [
      invoke(pick.deliverySlipsCancel, overrides.deliverySlipsCancel),
      invoke(pick.deliverySlipsUncancel, overrides.deliverySlipsUncancel),
      invoke(pick.invoicesCancel, overrides.invoicesCancel),
      invoke(pick.invoicesUncancel, overrides.invoicesUncancel),
      invoke(pick.paymentNoticesCancel, overrides.paymentNoticesCancel),
      invoke(pick.paymentNoticesUncancel, overrides.paymentNoticesUncancel),
      invoke(pick.purchaseOrdersCancel, overrides.purchaseOrdersCancel),
      invoke(pick.purchaseOrdersUncancel, overrides.purchaseOrdersUncancel),
      invoke(pick.quotationsCancel, overrides.quotationsCancel),
      invoke(pick.quotationsUncancel, overrides.quotationsUncancel),
      invoke(pick.receiptsCancel, overrides.receiptsCancel),
      invoke(pick.receiptsUncancel, overrides.receiptsUncancel),
      invoke(pick.deliverySlipsTemplatesIndex, overrides.deliverySlipsTemplatesIndex),
      invoke(pick.invoicesTemplatesIndex, overrides.invoicesTemplatesIndex),
      invoke(pick.paymentNoticesTemplatesIndex, overrides.paymentNoticesTemplatesIndex),
      invoke(pick.purchaseOrdersTemplatesIndex, overrides.purchaseOrdersTemplatesIndex),
      invoke(pick.quotationsTemplatesIndex, overrides.quotationsTemplatesIndex),
      invoke(pick.receiptsTemplatesIndex, overrides.receiptsTemplatesIndex),
      invoke(pick.deliverySlipsShow, overrides.deliverySlipsShow),
      invoke(pick.deliverySlipsUpdate, overrides.deliverySlipsUpdate),
      invoke(pick.invoicesShow, overrides.invoicesShow),
      invoke(pick.invoicesUpdate, overrides.invoicesUpdate),
      invoke(pick.paymentNoticesShow, overrides.paymentNoticesShow),
      invoke(pick.paymentNoticesUpdate, overrides.paymentNoticesUpdate),
      invoke(pick.purchaseOrdersShow, overrides.purchaseOrdersShow),
      invoke(pick.purchaseOrdersUpdate, overrides.purchaseOrdersUpdate),
      invoke(pick.quotationsShow, overrides.quotationsShow),
      invoke(pick.quotationsUpdate, overrides.quotationsUpdate),
      invoke(pick.receiptsShow, overrides.receiptsShow),
      invoke(pick.receiptsUpdate, overrides.receiptsUpdate),
      invoke(pick.deliverySlipsIndex, overrides.deliverySlipsIndex),
      invoke(pick.deliverySlipsCreate, overrides.deliverySlipsCreate),
      invoke(pick.invoicesIndex, overrides.invoicesIndex),
      invoke(pick.invoicesCreate, overrides.invoicesCreate),
      invoke(pick.paymentNoticesIndex, overrides.paymentNoticesIndex),
      invoke(pick.paymentNoticesCreate, overrides.paymentNoticesCreate),
      invoke(pick.purchaseOrdersIndex, overrides.purchaseOrdersIndex),
      invoke(pick.purchaseOrdersCreate, overrides.purchaseOrdersCreate),
      invoke(pick.quotationsIndex, overrides.quotationsIndex),
      invoke(pick.quotationsCreate, overrides.quotationsCreate),
      invoke(pick.receiptsIndex, overrides.receiptsIndex),
      invoke(pick.receiptsCreate, overrides.receiptsCreate),
    ];
  };
  return { all, pick };
}
