// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeliverySlipsCancelData,
  DeliverySlipsCancelErrors,
  DeliverySlipsCancelResponses,
  DeliverySlipsCreateData,
  DeliverySlipsCreateErrors,
  DeliverySlipsCreateResponses,
  DeliverySlipsIndexData,
  DeliverySlipsIndexErrors,
  DeliverySlipsIndexResponses,
  DeliverySlipsShowData,
  DeliverySlipsShowErrors,
  DeliverySlipsShowResponses,
  DeliverySlipsTemplatesIndexData,
  DeliverySlipsTemplatesIndexErrors,
  DeliverySlipsTemplatesIndexResponses,
  DeliverySlipsUncancelData,
  DeliverySlipsUncancelErrors,
  DeliverySlipsUncancelResponses,
  DeliverySlipsUpdateData,
  DeliverySlipsUpdateErrors,
  DeliverySlipsUpdateResponses,
  InvoicesCancelData,
  InvoicesCancelErrors,
  InvoicesCancelResponses,
  InvoicesCreateData,
  InvoicesCreateErrors,
  InvoicesCreateResponses,
  InvoicesIndexData,
  InvoicesIndexErrors,
  InvoicesIndexResponses,
  InvoicesShowData,
  InvoicesShowErrors,
  InvoicesShowResponses,
  InvoicesTemplatesIndexData,
  InvoicesTemplatesIndexErrors,
  InvoicesTemplatesIndexResponses,
  InvoicesUncancelData,
  InvoicesUncancelErrors,
  InvoicesUncancelResponses,
  InvoicesUpdateData,
  InvoicesUpdateErrors,
  InvoicesUpdateResponses,
  PaymentNoticesCancelData,
  PaymentNoticesCancelErrors,
  PaymentNoticesCancelResponses,
  PaymentNoticesCreateData,
  PaymentNoticesCreateErrors,
  PaymentNoticesCreateResponses,
  PaymentNoticesIndexData,
  PaymentNoticesIndexErrors,
  PaymentNoticesIndexResponses,
  PaymentNoticesShowData,
  PaymentNoticesShowErrors,
  PaymentNoticesShowResponses,
  PaymentNoticesTemplatesIndexData,
  PaymentNoticesTemplatesIndexErrors,
  PaymentNoticesTemplatesIndexResponses,
  PaymentNoticesUncancelData,
  PaymentNoticesUncancelErrors,
  PaymentNoticesUncancelResponses,
  PaymentNoticesUpdateData,
  PaymentNoticesUpdateErrors,
  PaymentNoticesUpdateResponses,
  PurchaseOrdersCancelData,
  PurchaseOrdersCancelErrors,
  PurchaseOrdersCancelResponses,
  PurchaseOrdersCreateData,
  PurchaseOrdersCreateErrors,
  PurchaseOrdersCreateResponses,
  PurchaseOrdersIndexData,
  PurchaseOrdersIndexErrors,
  PurchaseOrdersIndexResponses,
  PurchaseOrdersShowData,
  PurchaseOrdersShowErrors,
  PurchaseOrdersShowResponses,
  PurchaseOrdersTemplatesIndexData,
  PurchaseOrdersTemplatesIndexErrors,
  PurchaseOrdersTemplatesIndexResponses,
  PurchaseOrdersUncancelData,
  PurchaseOrdersUncancelErrors,
  PurchaseOrdersUncancelResponses,
  PurchaseOrdersUpdateData,
  PurchaseOrdersUpdateErrors,
  PurchaseOrdersUpdateResponses,
  QuotationsCancelData,
  QuotationsCancelErrors,
  QuotationsCancelResponses,
  QuotationsCreateData,
  QuotationsCreateErrors,
  QuotationsCreateResponses,
  QuotationsIndexData,
  QuotationsIndexErrors,
  QuotationsIndexResponses,
  QuotationsShowData,
  QuotationsShowErrors,
  QuotationsShowResponses,
  QuotationsTemplatesIndexData,
  QuotationsTemplatesIndexErrors,
  QuotationsTemplatesIndexResponses,
  QuotationsUncancelData,
  QuotationsUncancelErrors,
  QuotationsUncancelResponses,
  QuotationsUpdateData,
  QuotationsUpdateErrors,
  QuotationsUpdateResponses,
  ReceiptsCancelData,
  ReceiptsCancelErrors,
  ReceiptsCancelResponses,
  ReceiptsCreateData,
  ReceiptsCreateErrors,
  ReceiptsCreateResponses,
  ReceiptsIndexData,
  ReceiptsIndexErrors,
  ReceiptsIndexResponses,
  ReceiptsShowData,
  ReceiptsShowErrors,
  ReceiptsShowResponses,
  ReceiptsTemplatesIndexData,
  ReceiptsTemplatesIndexErrors,
  ReceiptsTemplatesIndexResponses,
  ReceiptsUncancelData,
  ReceiptsUncancelErrors,
  ReceiptsUncancelResponses,
  ReceiptsUpdateData,
  ReceiptsUpdateErrors,
  ReceiptsUpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * 納品書一覧の取得
 *
 *
 * 納品書の一覧を返します。
 */
export const deliverySlipsIndex = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsIndexData, ThrowOnError>,
): RequestResult<DeliverySlipsIndexResponses, DeliverySlipsIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    DeliverySlipsIndexResponses,
    DeliverySlipsIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips",
    ...options,
  });

/**
 * 納品書の作成
 *
 *
 * 納品書の作成をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const deliverySlipsCreate = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsCreateData, ThrowOnError>,
): RequestResult<DeliverySlipsCreateResponses, DeliverySlipsCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    DeliverySlipsCreateResponses,
    DeliverySlipsCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な納品書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な納品書の帳票テンプレート一覧を返します。
 */
export const deliverySlipsTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsTemplatesIndexData, ThrowOnError>,
): RequestResult<
  DeliverySlipsTemplatesIndexResponses,
  DeliverySlipsTemplatesIndexErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    DeliverySlipsTemplatesIndexResponses,
    DeliverySlipsTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips/templates",
    ...options,
  });

/**
 * 納品書の取得
 *
 *
 * 指定されたIDの納品書を返します。
 */
export const deliverySlipsShow = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsShowData, ThrowOnError>,
): RequestResult<DeliverySlipsShowResponses, DeliverySlipsShowErrors, ThrowOnError> =>
  (options.client ?? client).get<DeliverySlipsShowResponses, DeliverySlipsShowErrors, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/delivery_slips/{id}",
      ...options,
    },
  );

/**
 * 納品書の更新
 *
 *
 * 納品書の更新をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const deliverySlipsUpdate = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsUpdateData, ThrowOnError>,
): RequestResult<DeliverySlipsUpdateResponses, DeliverySlipsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<
    DeliverySlipsUpdateResponses,
    DeliverySlipsUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 納品書の取消
 *
 *
 * 指定された納品書を取消状態にします。
 *
 * 取引が紐づいている場合は取引も削除されます。
 */
export const deliverySlipsCancel = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsCancelData, ThrowOnError>,
): RequestResult<DeliverySlipsCancelResponses, DeliverySlipsCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    DeliverySlipsCancelResponses,
    DeliverySlipsCancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された納品書の復元
 *
 *
 * 指定された取消済み納品書を復元します。
 */
export const deliverySlipsUncancel = <ThrowOnError extends boolean = true>(
  options: Options<DeliverySlipsUncancelData, ThrowOnError>,
): RequestResult<DeliverySlipsUncancelResponses, DeliverySlipsUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    DeliverySlipsUncancelResponses,
    DeliverySlipsUncancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/delivery_slips/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 請求書一覧の取得
 *
 */
export const invoicesIndex = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesIndexData, ThrowOnError>,
): RequestResult<InvoicesIndexResponses, InvoicesIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<InvoicesIndexResponses, InvoicesIndexErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices",
    ...options,
  });

/**
 * 請求書の作成
 *
 *
 * 請求書の作成をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const invoicesCreate = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesCreateData, ThrowOnError>,
): RequestResult<InvoicesCreateResponses, InvoicesCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<InvoicesCreateResponses, InvoicesCreateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な請求書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な請求書の帳票テンプレート一覧を返します。
 */
export const invoicesTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesTemplatesIndexData, ThrowOnError>,
): RequestResult<InvoicesTemplatesIndexResponses, InvoicesTemplatesIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    InvoicesTemplatesIndexResponses,
    InvoicesTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices/templates",
    ...options,
  });

/**
 * 請求書の取得
 *
 *
 * 指定されたIDの請求書を返します。
 */
export const invoicesShow = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesShowData, ThrowOnError>,
): RequestResult<InvoicesShowResponses, InvoicesShowErrors, ThrowOnError> =>
  (options.client ?? client).get<InvoicesShowResponses, InvoicesShowErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices/{id}",
    ...options,
  });

/**
 * 請求書の更新
 *
 *
 * 請求書の更新をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const invoicesUpdate = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesUpdateData, ThrowOnError>,
): RequestResult<InvoicesUpdateResponses, InvoicesUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<InvoicesUpdateResponses, InvoicesUpdateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 請求書の取消
 *
 *
 * 指定された請求書を取消状態にします。
 *
 * 取引が紐づいている場合は取引も削除されます。
 */
export const invoicesCancel = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesCancelData, ThrowOnError>,
): RequestResult<InvoicesCancelResponses, InvoicesCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<InvoicesCancelResponses, InvoicesCancelErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された請求書の復元
 *
 *
 * 指定された取消済み請求書を復元します。
 */
export const invoicesUncancel = <ThrowOnError extends boolean = true>(
  options: Options<InvoicesUncancelData, ThrowOnError>,
): RequestResult<InvoicesUncancelResponses, InvoicesUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<InvoicesUncancelResponses, InvoicesUncancelErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/invoices/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 支払通知書一覧の取得
 *
 */
export const paymentNoticesIndex = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesIndexData, ThrowOnError>,
): RequestResult<PaymentNoticesIndexResponses, PaymentNoticesIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    PaymentNoticesIndexResponses,
    PaymentNoticesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices",
    ...options,
  });

/**
 * 支払通知書の作成
 *
 *
 * 支払通知書の作成をします。
 */
export const paymentNoticesCreate = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesCreateData, ThrowOnError>,
): RequestResult<PaymentNoticesCreateResponses, PaymentNoticesCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PaymentNoticesCreateResponses,
    PaymentNoticesCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な支払通知書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な支払通知書の帳票テンプレート一覧を返します。
 */
export const paymentNoticesTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesTemplatesIndexData, ThrowOnError>,
): RequestResult<
  PaymentNoticesTemplatesIndexResponses,
  PaymentNoticesTemplatesIndexErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PaymentNoticesTemplatesIndexResponses,
    PaymentNoticesTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices/templates",
    ...options,
  });

/**
 * 支払通知書の取得
 *
 *
 * 指定されたIDの支払通知書を返します。
 */
export const paymentNoticesShow = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesShowData, ThrowOnError>,
): RequestResult<PaymentNoticesShowResponses, PaymentNoticesShowErrors, ThrowOnError> =>
  (options.client ?? client).get<
    PaymentNoticesShowResponses,
    PaymentNoticesShowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices/{id}",
    ...options,
  });

/**
 * 支払通知書の更新
 *
 *
 * 支払通知書の更新をします。
 */
export const paymentNoticesUpdate = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesUpdateData, ThrowOnError>,
): RequestResult<PaymentNoticesUpdateResponses, PaymentNoticesUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PaymentNoticesUpdateResponses,
    PaymentNoticesUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 支払通知書の取消
 *
 *
 * 指定された支払通知書を取消状態にします。
 *
 * 取引が紐づいている場合は取引も削除されます。
 */
export const paymentNoticesCancel = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesCancelData, ThrowOnError>,
): RequestResult<PaymentNoticesCancelResponses, PaymentNoticesCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PaymentNoticesCancelResponses,
    PaymentNoticesCancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された支払通知書の復元
 *
 *
 * 指定された取消済み支払通知書を復元します。
 */
export const paymentNoticesUncancel = <ThrowOnError extends boolean = true>(
  options: Options<PaymentNoticesUncancelData, ThrowOnError>,
): RequestResult<PaymentNoticesUncancelResponses, PaymentNoticesUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PaymentNoticesUncancelResponses,
    PaymentNoticesUncancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/payment_notices/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 発注書一覧の取得
 *
 *
 * 発注書の一覧を返します。
 */
export const purchaseOrdersIndex = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersIndexData, ThrowOnError>,
): RequestResult<PurchaseOrdersIndexResponses, PurchaseOrdersIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    PurchaseOrdersIndexResponses,
    PurchaseOrdersIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders",
    ...options,
  });

/**
 * 発注書の作成
 *
 *
 * 発注書の作成をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const purchaseOrdersCreate = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersCreateData, ThrowOnError>,
): RequestResult<PurchaseOrdersCreateResponses, PurchaseOrdersCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PurchaseOrdersCreateResponses,
    PurchaseOrdersCreateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な発注書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な発注書の帳票テンプレート一覧を返します。
 */
export const purchaseOrdersTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersTemplatesIndexData, ThrowOnError>,
): RequestResult<
  PurchaseOrdersTemplatesIndexResponses,
  PurchaseOrdersTemplatesIndexErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PurchaseOrdersTemplatesIndexResponses,
    PurchaseOrdersTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders/templates",
    ...options,
  });

/**
 * 発注書の取得
 *
 *
 * 指定されたIDの発注書を返します。
 */
export const purchaseOrdersShow = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersShowData, ThrowOnError>,
): RequestResult<PurchaseOrdersShowResponses, PurchaseOrdersShowErrors, ThrowOnError> =>
  (options.client ?? client).get<
    PurchaseOrdersShowResponses,
    PurchaseOrdersShowErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders/{id}",
    ...options,
  });

/**
 * 発注書の更新
 *
 *
 * 発注書の更新をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const purchaseOrdersUpdate = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersUpdateData, ThrowOnError>,
): RequestResult<PurchaseOrdersUpdateResponses, PurchaseOrdersUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PurchaseOrdersUpdateResponses,
    PurchaseOrdersUpdateErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 発注書の取消
 *
 *
 * 指定された発注書を取消状態にします。
 *
 * 取引が紐づいている場合は取引も削除されます。
 */
export const purchaseOrdersCancel = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersCancelData, ThrowOnError>,
): RequestResult<PurchaseOrdersCancelResponses, PurchaseOrdersCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PurchaseOrdersCancelResponses,
    PurchaseOrdersCancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された発注書の復元
 *
 *
 * 指定された取消済み発注書を復元します。
 */
export const purchaseOrdersUncancel = <ThrowOnError extends boolean = true>(
  options: Options<PurchaseOrdersUncancelData, ThrowOnError>,
): RequestResult<PurchaseOrdersUncancelResponses, PurchaseOrdersUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    PurchaseOrdersUncancelResponses,
    PurchaseOrdersUncancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/purchase_orders/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 見積書一覧の取得
 *
 */
export const quotationsIndex = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsIndexData, ThrowOnError>,
): RequestResult<QuotationsIndexResponses, QuotationsIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<QuotationsIndexResponses, QuotationsIndexErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations",
    ...options,
  });

/**
 * 見積書の作成
 *
 *
 * 見積書の作成をします。
 */
export const quotationsCreate = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsCreateData, ThrowOnError>,
): RequestResult<QuotationsCreateResponses, QuotationsCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<QuotationsCreateResponses, QuotationsCreateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な見積書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な見積書の帳票テンプレート一覧を返します。
 */
export const quotationsTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsTemplatesIndexData, ThrowOnError>,
): RequestResult<QuotationsTemplatesIndexResponses, QuotationsTemplatesIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    QuotationsTemplatesIndexResponses,
    QuotationsTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations/templates",
    ...options,
  });

/**
 * 見積書の取得
 *
 *
 * 指定されたIDの見積書を返します。
 */
export const quotationsShow = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsShowData, ThrowOnError>,
): RequestResult<QuotationsShowResponses, QuotationsShowErrors, ThrowOnError> =>
  (options.client ?? client).get<QuotationsShowResponses, QuotationsShowErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations/{id}",
    ...options,
  });

/**
 * 見積書の更新
 *
 *
 * 見積書の更新をします。
 */
export const quotationsUpdate = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsUpdateData, ThrowOnError>,
): RequestResult<QuotationsUpdateResponses, QuotationsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<QuotationsUpdateResponses, QuotationsUpdateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 見積書の取消
 *
 *
 * 指定された見積書を取消状態にします。
 */
export const quotationsCancel = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsCancelData, ThrowOnError>,
): RequestResult<QuotationsCancelResponses, QuotationsCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<QuotationsCancelResponses, QuotationsCancelErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された見積書の復元
 *
 *
 * 指定された取消済み見積書を復元します。
 */
export const quotationsUncancel = <ThrowOnError extends boolean = true>(
  options: Options<QuotationsUncancelData, ThrowOnError>,
): RequestResult<QuotationsUncancelResponses, QuotationsUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<
    QuotationsUncancelResponses,
    QuotationsUncancelErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/quotations/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 領収書一覧の取得
 *
 *
 * 領収書の一覧を返します。
 */
export const receiptsIndex = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsIndexData, ThrowOnError>,
): RequestResult<ReceiptsIndexResponses, ReceiptsIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<ReceiptsIndexResponses, ReceiptsIndexErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts",
    ...options,
  });

/**
 * 領収書の作成
 *
 *
 * 領収書の作成をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const receiptsCreate = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsCreateData, ThrowOnError>,
): RequestResult<ReceiptsCreateResponses, ReceiptsCreateErrors, ThrowOnError> =>
  (options.client ?? client).post<ReceiptsCreateResponses, ReceiptsCreateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 使用可能な領収書の帳票テンプレート一覧の取得
 *
 *
 * 使用可能な領収書の帳票テンプレート一覧を返します。
 */
export const receiptsTemplatesIndex = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsTemplatesIndexData, ThrowOnError>,
): RequestResult<ReceiptsTemplatesIndexResponses, ReceiptsTemplatesIndexErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ReceiptsTemplatesIndexResponses,
    ReceiptsTemplatesIndexErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts/templates",
    ...options,
  });

/**
 * 領収書の取得
 *
 *
 * 指定されたIDの領収書を返します。
 */
export const receiptsShow = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsShowData, ThrowOnError>,
): RequestResult<ReceiptsShowResponses, ReceiptsShowErrors, ThrowOnError> =>
  (options.client ?? client).get<ReceiptsShowResponses, ReceiptsShowErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts/{id}",
    ...options,
  });

/**
 * 領収書の更新
 *
 *
 * 領収書の更新をします。
 *
 * issue_date, account_item_id, tax_code, item_id, section_id, tag_ids, segment_1_tag_id, segment_2_tag_id, segment_3_tag_id は、取引登録の下書き保存で利用されます。
 *
 * tag_idsは10個まで設定可能です。
 */
export const receiptsUpdate = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsUpdateData, ThrowOnError>,
): RequestResult<ReceiptsUpdateResponses, ReceiptsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).put<ReceiptsUpdateResponses, ReceiptsUpdateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 領収書の取消
 *
 *
 * 指定された領収書を取消状態にします。
 *
 * 取引が紐づいている場合は取引も削除されます。
 */
export const receiptsCancel = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsCancelData, ThrowOnError>,
): RequestResult<ReceiptsCancelResponses, ReceiptsCancelErrors, ThrowOnError> =>
  (options.client ?? client).put<ReceiptsCancelResponses, ReceiptsCancelErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts/{id}/cancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取消された領収書の復元
 *
 *
 * 指定された取消済み領収書を復元します。
 */
export const receiptsUncancel = <ThrowOnError extends boolean = true>(
  options: Options<ReceiptsUncancelData, ThrowOnError>,
): RequestResult<ReceiptsUncancelResponses, ReceiptsUncancelErrors, ThrowOnError> =>
  (options.client ?? client).put<ReceiptsUncancelResponses, ReceiptsUncancelErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/receipts/{id}/uncancel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
